bool isUpgradedPiece(char piece);
int relativeDirectionOf(int player);
bool movesLikeGold(char piece);
int goldLegalMove(int player, int *src, int *dst);
int silverLegalMove(int player, int *src, int *dst);
int kingLegalMove(int player, int *src, int *dst);
int lanceLegalMove(char board[9][9], int player, int *src, int *dst);
int bishopLegalMove(char board[9][9], int player, int *src, int *dst);
int upBishopLegalMove(int player, int *src, int *dst);
int rookLegalDirection(int *src, int *dst);
int rookLegalMove(char board[9][9], int player, int *src, int *dst);
int upRookLegalMove(int player, int *src, int *dst);
int pawnLegalMove(int player, int *src, int *dst);
int inRange(int rank, int file);
int legalSrc(char piece, int player, int rank, int file);
int legalDest(char board[9][9], int player, int rank, int file);
int inGraveyard(char graveyard[2][38], int player, char piece);
bool isUpgradablePiece(char piece);
bool isUpgradedPiece(char piece);
